# Generated by Django 5.1.2 on 2024-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(default=0, upload_to='plant_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plants',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
