# Generated by Django 5.1.2 on 2024-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0002_plants_image_alter_plants_name_alter_plants_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='image',
        ),
        migrations.AlterField(
            model_name='plants',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
